### ISSUE TITLE
Version Tracking: v3.2.4

### ISSUE THREAD

**Issue by prasannavl** [DeFiCh/ain#1750]
# Items

- [x] Fix for DeFiCh/team#32
  - https://github.com/DeFiCh/ain/pull/1700
- [x] Fix for https://github.com/DeFiCh/ain/issues/1680 
  - https://github.com/DeFiCh/ain/pull/1715
- [x] Temporary mitigation to prevent NEUTRAL votes on the RPC: https://github.com/DeFiCh/ain/issues/1704
  - https://github.com/DeFiCh/ain/pull/1709
- [x] https://github.com/DeFiCh/ain/pull/1719
- [x] https://github.com/DeFiCh/ain/issues/1721
  - [x] https://github.com/DeFiCh/ain/pull/1722
  - [x] https://github.com/DeFiCh/ain/pull/1725
- [x] https://github.com/DeFiCh/ain/pull/1705
- [x] https://github.com/DeFiCh/ain/pull/1712
- [x] https://github.com/DeFiCh/ain/pull/1715
- [x] https://github.com/DeFiCh/ain/pull/1717
- [x] Fix for https://github.com/DeFiCh/ain/pull/1740
  - https://github.com/DeFiCh/ain/pull/1714
- [x] https://github.com/DeFiCh/ain/pull/1701
- [x] Fix for https://github.com/DeFiCh/ain/pull/1741 and https://github.com/DeFiCh/ain/issues/1737
- [x] Fix for https://github.com/DeFiCh/ain/pull/1742 and https://github.com/DeFiCh/ain/issues/1739
- [x] Bump version

# Verification

- [x] Full reindexed data comparison with 3.2.2 (See below)
  - [x] Account history diff (Reason: Overall accounting impact) 
  - [x] Burninfo diff - (Reason: negative interest impact)
