### ISSUE TITLE
DeFiChain xVM: EVM Tracker

### ISSUE THREAD

**Issue by prasannavl** [DeFiCh/ain#1961]
## Summary

- High-level tracker for all xVM foundations and EVM.
- Release Tracker: https://github.com/DeFiCh/ain/issues/2535
- Bug Tracker: https://github.com/DeFiCh/ain/issues/1991
- [ETH-JSON Spec Implementation Tracker](https://github.com/DeFiCh/ain/issues/1852)

## Infrastructure

- [x] Repository cleanup + toolchain upgrades 
  - https://github.com/DeFiCh/ain/compare/bbc84f2feae6a89fb5a327276c4c01cba5d51728...5c24e4096d55650a3f0bc270e1fda1c7ed7cc39a
- [x] Rust-lang toolchain integration
- [x] C++-Rust FFI layer 
- [ ] :no_entry: Protobuf + GRPC toolchain [Shelved]
 - https://github.com/DeFiCh/ain/pull/1959
- [x] Sputnik VM integration
- [x] RocksDB layer
- [x] Other scaffolds
  - https://github.com/DeFiCh/ain/pull/1953
  - https://github.com/DeFiCh/ain/pull/1955
  - https://github.com/DeFiCh/ain/pull/1952

## xVM Foundations

- [x] Port of EVM Transaction (EVMTx)
  - https://github.com/DeFiCh/ain/pull/1958
  - https://github.com/DeFiCh/ain/pull/1956
- [x] Port of EVMTx Mining
  - https://github.com/DeFiCh/ain/pull/1954
  - https://github.com/DeFiCh/ain/pull/1957
- [x] Abstract into xVM with xVM Interconnect (Partially, rest postponed)
- [x] `TransferDomain`
  - [x] Port of `TransferBalance`
  - [x] Finalize `TransferDomain` API

## EVM Support

- [x] ETH Address
  - https://github.com/DeFiCh/ain/pull/1951
- [x] EVM Validation
- [x] EVM State Persistence
- [ ] :no_entry: ETH GRPC [Shelved]
- [x] [ETH-JSON RPC](https://github.com/DeFiCh/ain/issues/1852)
