### ISSUE TITLE
Metachain ts suites checklist

### ISSUE THREAD

**Issue by canonbrother** [DeFiCh/ain#2167]
### Summary 

Open issue to track metachain ts suites. 

#### 1. Genesis Block
- [x] genesis balance is setup correctly
- [x] balance to be updated after transfer

#### 2. Metachain RPC (BlockNumber tags)
- [x] `earliest` returns genesis
- [x] `latest` returns `BlockchainInfo::best_hash` number

> not ready yet

~~- [ ] `finalized` uses `BlockchainInfo::finalized_hash`  number~~
~~- [ ] `safe` is an alias for `finalized` in Polkadot~~

#### 3. Metachain RPC (Block)
- [x] should be at block 1
- [x] should return genesis block by number
- [x] should have empty uncles and correct sha3Uncles
- [x] should have empty transactions and correct transactionRoot
- [x] should be at block 2 after block production (block 1 is at beginning in defi ecosys)
- [x] should have valid timestamp after block production
- [x] should return current block by latest
- [x] genesis block should be already available by hash
- [x] retrieve block information
- [x] get block by hash
- [x] get block by number
- [x] should include previous block hash as parent

#### 4. Metachain RPC (Bloom)
- [x] receipt data should be in bloom

#### 5. Metachain RPC (Contract Methods)
- [x] get transaction by hash
- [x] should return contract method result
- [x] should get correct environmental block number
- [x] should get correct environmental block gaslimit

> `blockhashcount` not ready yet

~~- [ ] should get correct environmental block hash~~

> err message mapping

~~- [ ] should fail for missing parameters~~
~~- [ ] should fail for too many parameters~~
~~- [ ] should fail for invalid parameters~~

#### 5a. Metachain RPC (Contract)
- [x] eth_getStorageAt
- [x] SSTORE cost should properly take into account transaction initial value**
- [x] contract creation should return transaction hash
- [x] eth_call contract create should return code
- [x] eth_call at missing block returns error

#### 6. Metachain RPC (Deprecated)
- [x] eth_getCompilers should be deprecated
- [x] eth_compileLLL should be deprecated
- [x] eth_compileSolidity should be deprecated
- [x] eth_compileSerpent should be deprecated

#### 7. Metachain RPC (estimate gas historically)
> not from origin test.. re-investigate after basic 

~~- [ ] estimate gas historically should work~~

#### 8. Metachain RPC (RPC execution)
- [x] should call with gas limit under block gas limit
- [x] should call with gas limit up to 10x block gas limit
- [x] should estimateGas with gas limit under block gas limit
- [x] `input` field alias is properly deserialized

> No config and validation yet

~~- [ ] shouldn't call with gas limit up higher than 10x block gas limit~~ 
~~- [ ] should estimateGas with gas limit up to 10x block gas limit~~
~~- [ ] shouldn't estimateGas with gas limit up higher than 10x block gas limit~~
~~- [ ] should use the gas limit multiplier fallback~~

#### 9. Metachain RPC (Fee History)
- [x] should return error on non-existent blocks
- [x] result length should match spec
- [x] should calculate percentiles

#### 10. Metachain RPC (EthFilterApi)
- [x] should create a Log filter and return the ID
- [x] should increment filter ID
- [x] should create a Block filter and return the ID
- [x] should return unsupported error for Pending Transaction filter creation
- [x] should return responses for Block filter polling.
- [x] should return responses for Log filter polling.
- [x] should return response for raw Log filter request.
- [x] should uninstall created filters.

> no block lifespan threshold configuration
~~- [ ] should drain the filter pool.~~

> no pool max size configuration
~~- [ ] should have a filter pool max size of 500.~~

#### 11. Metachain RPC (Gas)
- [x] eth_estimateGas for contract creation

> Skip by default

~~- [ ] block gas limit over 5M~~
~~- [ ] gas limit should decrease on next block if gas unused~~
~~- [ ] gas limit should increase on next block if gas fully used~~

#### 11a. Estimate Gas
- [x] eth_estimateGas for contract call
- [x] eth_estimateGas without gas_limit should pass
- [x] eth_estimateGas should handle AccessList alias
- [x] eth_estimateGas 0x0 gasPrice is equivalent to not setting one

#### 11b. Gas Limit
- [x] tx gas limit below ETH_BLOCK_GAS_LIMIT
- [x] tx gas limit equal ETH_BLOCK_GAS_LIMIT
- [x] tx gas limit larger ETH_BLOCK_GAS_LIMIT

#### 12. Metachain RPC (Invalid opcode estimate gas)
> test is for estimate mode on

~~- [ ] should estimate gas with invalid opcode~~

#### 13. Metachain RPC (Log filtering)
- [x] EthFilterApi::getFilterLogs - should filter out non-matching cases.
- [x] EthApi::getLogs - should filter out non-matching cases.

#### 14. Metachain RPC (Log BlockNumber tags)
- [x] **PREV PASSED: EthFilterApi::getFilterLogs - should handle earliest and latest tags**
- [x] EthApi::getLogs - should handle earliest and latest tags

#### 15. Metachain RPC (Max Priority Fee Per Gas)
- [x] should default to zero on genesis
- [x] should default to zero on empty blocks
- [x] maxPriorityFeePerGas should suggest the percentile 60 tip
- [x] maxPriorityFeePerGas should suggest zero if there are recent empty blocks

#### 16. Metachain RPC (Net)
- [x] should return `net_version`
> Not ready yet
~~- [ ] should return `peer_count` in hex directly using the provider~~
~~- [ ] should format `peer_count` as decimal using `web3.net`~~

#### 17. Metachain RPC (Nonce)
- [x] get nonce

#### 18. Metachain RPC (Pending Pool)
> Not ready yet
~~- [ ] should return a pending transaction~~

#### 19. Metachain RPC (Pending Transaction Count)
> `tags` is not working on `eth_getTransactionCount`
~~- [ ] should return pending transaction count~~

#### 20. Metachain RPC (Precompile)
- [x] should perform ecrecover
- [x] should perform identity directly

#### 21. Metachain RPC (Revert Reason)
- [x] should fail with revert reason

#### 22. Metachain RPC (Constructor Revert)
- [x] should provide a tx receipt after successful deployment
- [x] should provide a tx receipt after failed deployment

#### 23. Metachain RPC (Constant)
- [x] should have 0 hashrate
- [x] should have chainId
- [x] should have no account
> Block author is removed
~~- [ ] block author should be 0x0000000000000000000000000000000000000000~~

#### 24. Metachain RPC (StateOverride)
> not ready yet
~~- [x] should have balance above 1000 tether without state override~~
~~- [ ] should have a sender balance of 4500 with state override~~
~~- [x] should have availableFunds of 100 without state override~~
~~- [ ] should have availableFunds of 500 with state override~~
~~- [x] should have allowance of 10 without state override~~
~~- [ ] should have allowance of 50 with state override~~
~~- [ ] should have allowance of 50 but availableFunds 0 with full state override~~
~~- [ ] should set MultiplyBy7 deployedBytecode with state override~~

#### 25. Metachain RPC (State root hash)
- [x] should calculate a valid intermediate state root hash
- [x] hash should be unique between blocks  https://github.com/DeFiCh/ain/pull/2213 revert https://github.com/DeFiCh/ain/commit/6d0a0f5999544b8e0dd1a6a57dc723dc4405055a

#### 26. Metachain RPC (Subscription)
> not ready yet
~~- [ ] should connect~~
~~- [ ] should subscribe~~
~~- [ ] should get newHeads stream~~
~~- [ ] should get newPendingTransactions stream~~
~~- [ ] should subscribe to all logs~~
~~- [ ] should subscribe to logs by multiple addresses~~
~~- [ ] should subscribe to logs by topic~~
~~- [ ] should get past events 1: by topic~~
~~- [ ] should get past events 2: by address~~
~~- [ ] should get past events 3: by address + topic~~
~~- [ ] should get past events 4: multiple addresses~~
~~- [ ] should support topic wildcards~~
~~- [ ] should support single values wrapped around a sequence~~
~~- [ ] should support topic conditional parameters~~
~~- [ ] should support multiple topic conditional parameters~~
~~- [ ] should combine topic wildcards and conditional parameters~~

#### 27. Metachain RPC (Transaction Cancellation)
- [x] should cancel the pre-transaction whilst sending tx with same nonce
- [x] should prioritize transaction with the higher gasPrice

#### 28. Metachain RPC (Transaction cost)
- [x] should take transaction cost into account and not submit it to the pool

#### 29. Metachain RPC (Transaction Version)
- [x] should handle Legacy transaction type 0
- [x] should handle EIP-2930 transaction type 1
- [x] should handle EIP-1559 transaction type 2

#### 30. Metachain RPC (Web3Api)
> Not ready yet
~~- [ ] should get client version~~
~~- [ ] should remote sha3~~

**Comment by canonbrother** [comment]
remaining check list: 

#### SSTORE
PREV PASSED: SSTORE cost should properly take into account transaction initial value

#### `eth_feeHistory`
result length should match spec
should calculate percentiles

#### `eth_getFilterChanges`
should return responses for Log filter polling.

(error msg remapped)
should drain the filter pool.

#### `eth_newFilter` & `eth_getFilterLogs`
PREV PASSED: EthFilterApi::getFilterLogs - should handle earliest and latest tags

#### `eth_maxPriorityFeePerGas`
maxPriorityFeePerGas should suggest the percentile 60 tip
maxPriorityFeePerGas should suggest zero if there are recent empty blocks
