### ISSUE TITLE
Metachain Upgrade Milestones Tracker 

### ISSUE THREAD

**Issue by prasannavl** [DeFiCh/ain#2535]
## Summary

- The Metachain Upgrade's key focus is DeFiChain's EVM and ETH-JSON RPC. 
  - More info on the specifics: https://github.com/DeFiCh/ain/issues/1961
- This issue is to gauge readiness and relevant information, along with all ecosystem level components.

# Milestones

## beta1..14
 
 - Completion of EVM implementation
 - Finalized consensus changes 
-  Completion of key ETH-JSON RPC

For rc: 

   - [x]  **changi** on beta stable
   - [x] **changi** on beta with no security bugs
   - :construction:  **changi** performance profiles look sufficient to support the ecosystem including infrastructure and tooling. 
      - [x] Node mempool
      - :construction: Node sync performance sufficient to support **testnet** 
          - SLOW, but can still keep the network going.
          -  Both Ocean as well as explorers are able to follow with both changi and simulated testnet.
          - Expect performance updates before stable.   
      - [x] Ocean: whale indexerer (supports DeFiScan)
      - [x] Ocean: Transaction builders (supports wallets)
      - [x] Ocean: Infrastructure orchestration, self-recovery sufficient to support **testnet**
 
 Latest release: https://github.com/DeFiCh/ain/releases/tag/v4.0.0-beta14
 
 ## rc
 
 #### High-level summary
 
 - The intended consensus are considered final at this point; And as such, release-candidate are considered stable to be able to support mainnet. Caveats might be perf. profiles. 
 
 - For stable: 
   - [x] **testnet** on rc stable
   - [x] **testnet** on rc with no security bugs
    - [x] **tesnet** performance profiles look sufficient to support the ecosystem including infrastructure and tooling. 
      - [x] Node mempool
      - [x] Node sync performance sufficient to support **mainnet**
      - [x] Ocean: whale indexerer (supports DeFiScan)
      - [x] Ocean: Transaction builders (supports wallets)
      - [x] Ocean: Infrastructure orchestration, self-recovery sufficient to support **mainnet**
 
 ### rc1
 
 - https://github.com/DeFiCh/ain/pull/2486
 
 #### Essential 
 
- [x] Mempool performance - OK 
  - [x] Mempool basics optimization 
     - Context: Over the last 2 weeks, mempool performance has increased over 100%-200% across varying workloads. Still work to be done, however should be sufficient enough for now.
  - [x] Miner: 10% fee increase requirement for Replace-By-Fee transactions 
    - Context: Important to prevents mempool spam with dust fee increases. 
- [x] Evaluation of Ocean performance for testnet
    - Context: It is expected that the performance of Ocean will be degraded and infrastructure costs will have temporary increase during testnet phase. Finish a proper evaluation to see if it's sufficient to sufficient to support and be able to able the planned performance improvement to be able to resolve this in time for mainnet.

#### Optional

- [x] Sync performance
  - Context: Current sync performance is thoroughly un-optimised which can result in stalls across infrastructure like Ocean that expect responses in time or go through self-recovery loops. 
  - Majority of it is due to triedb commits. 
    - [x] Short-term: In-memory cache and reduce state root commit phases. 
    - Long-term: Roll-out a more integrated impl over rocksdb.
