### ISSUE TITLE
Ocean tracker

### ISSUE THREAD

**Issue by Jouzo** [DeFiCh/ain#2763]
## Summary

- [x] Add axum REST server
- [x] Add ocean API routers
- [x] Ocean models
- [x] Ocean server init
- [x] RocksDB structures to index @nagarajm22 https://github.com/DeFiCh/ain/pull/2728
- [x] CI test suite @canonbrother https://github.com/DeFiCh/ain/pull/2734
- [x] Pagination support @canonbrother https://github.com/DeFiCh/ain/pull/2737
- [x] `ocean-archive` node flag @Jouzo https://github.com/DeFiCh/ain/pull/2724/commits/fb1b8323c9e4d9859817e4dc1ddbd5a8440a2bb1

## WIP
- [ ] API typing @canonbrother 
- [ ] Process block and index TXs as required - Started in 3e11241d1d16092e0d6aff20c75725f5f46fb987
- [ ] Controllers logic
- [ ] Proxy cached endpoints to existing JSON-RPC endpoints
    - [ ] Add caching layer
    - [ ] Extract inner RPC logic and expose via FFI
        - [ ] account.getAccount
        - [ ] account.getAccountHistory
        - [ ] account.getBurnInfo
        - [ ] account.listAccountHistory
        - [ ] blockchain.getBlockchainInfo
        - [ ] loan.getLoanInfo
        - [ ] loan.getLoanScheme
        - [ ] masternode.getGov
        - [ ] net.getNetworkInfo
        - [ ] poolpair.getPoolPair
        - [ ] poolpair.listPoolPairs
        - [ ] token.getToken
        - [ ] token.listTokens
- [ ] Additional index for verbose poolswap information
- [ ] Handle secondary indexes for iteration
- [ ] Set ocean API port in params

**Comment by Jouzo** [comment]
Block indexing @canonbrother

**Comment by canonbrother** [comment]
## Test suites checklist
#### loan.collateral.controller.defid.ts
list
  - [ ] should listCollateralTokens
  - [x] should listCollateralTokens with pagination
  - [x] should listCollateralTokens with an empty object if size 100 next 300 which is out of range
get
  - [ ] should get collateral token by symbol
  - [x] should throw error while getting non-existent collateral token id
#### loan.token.controller.defid.ts
list
  - [ ] should listLoanTokens
  - [ ] should listLoanTokens with pagination
  - [x] should listLoanTokens with an empty object if size 100 next 300 which is out of range
get
  - [ ] should get loan token by symbol
  - [ ] should throw error while getting non-existent loan token id

#### transaction.controller.defid.ts
get
  - [ ] should get a single transaction
  - [x] should due to non-existent transaction
getVins
  - [x] should return list of vin
  - [x] should return empty page if txid is not valid
  ○ skipped should return list of vin when next is out of range
getVouts
  - [x] should return list of vout (3 ms)
  - [x] should return empty page if txid is not valid
  ○ skipped should return list of vout when next is out of range

#### poolpair.fees.service.defid.ts
get best path - DEX burn fees
  - [ ] should return fees - CAT to DFI - Both token fees direction are in
  - [ ] should return fees - DFI to CAT - Both token fees direction are in
  - [ ] should return fees - DFI to DOG - Both token fees direction is out
  - [ ] should return fees - DOG to DFI - Both token fees direction is out
  - [ ] should return fees - KOALA to DFI - TokenA fee direction is in
  - [ ] should return fees - DFI to KOALA - TokenA fee direction is in
  - [ ] should return fees - FISH to DFI - TokenB fee direction is out
  - [ ] should return fees - DFI to FISH - TokenB fee direction is out
  - [ ] should return fees (bidirectional) - DFI <-> TURTLE - TokenA fee direction is both
  - [ ] should return fees (bidirectional) - DFI <-> PANDA - TokenA fee direction is both
  - [ ] should return fees (bidirectional) - DFI <-> RABBIT - Both token fees direction are both
  - [ ] should return fees (bidirectional) - DFI <-> FOX - if tokenA fee direction is not set
  - [ ] should return fees (bidirectional) - DFI <-> LION - if tokenB fee direction is not set
  - [ ] should return fees (bidirectional) - DFI <-> TIGER - if both token fees direction are not set
  - [ ] should return [] if dex fees is not set

get best path - DEX estimated return
  - [ ] should less dex fees in estimatedReturnLessDexFees - 1 leg
  - [ ] should less dex fees in estimatedReturnLessDexFees - 2 legs
  - [ ] should not less dex fees if dex fees is not set

#### poolpair.swap.controller.defid.ts
poolswap buy-sell indicator
  - [ ] should get pool swap details
  - [ ] should get composite pool swap for 2 jumps
  - [ ] should get composite pool swap for 2 jumps scenario 2
  - [ ] should get composite pool swap for 3 jumps
  - [ ] should get direct pool swap for composite swap

#### masternode.controller.defid.ts
list
  - [x] should list masternodes
  - [x] should list masternodes with pagination
get
  - [x] should get a masternode with id
  - [x] should due to non-existent masternode
resign
  - [ ] should get masternode with pre-resigned state
timelock
  - [x] should get masternode with timelock

#### poolpair.swap.verbose.controller.defid.ts
poolswap buy-sell indicator
  - [ ] should get pool swap details
  - [ ] should get composite pool swap for 2 jumps
  - [ ] should get composite pool swap for 2 jumps scenario 2
  - [ ] should get composite pool swap for 3 jumps
  - [ ] should get direct pool swap for composite swap

#### loan.vault.controller.defid.ts
  loan
    - [ ] should listVaults with size only
  get
    - [ ] should get vault by vaultId
    - [ ] should throw error while getting non-existent vault
#### rawtx.controller.defid.ts
test
  - [x] should accept valid txn (18 ms)
  - [x] should accept valid txn with given maxFeeRate
  - [ ] should throw BadRequestError due to invalid txn
  - [ ] should throw BadRequestError due to high fees
send
  - [ ] should send valid txn and validate tx out
  - [ ] should send valid txn with given maxFeeRate and validate tx out
  - [ ] should throw BadRequestException due to invalid txn
  - [ ] should throw BadRequestException due to high fees
get
  - [ ] should accept valid txn and return hex
  - [ ] should throw NotFoundException due to tx id not found

#### poolpair.controller.defid.ts
list
  - [ ] should list
  - [ ] should list with pagination
  - [ ] should list with undefined next pagination
get
  - [ ] should get (5 ms)
  - [ ] should throw error while getting non-existent poolpair
get best path
  - [ ] should be bidirectional swap path - listPaths(a, b) === listPaths(b, a)
  - [ ] should get best swap path - 2 legs
  - [ ] should get correct swap path - 3 legs
  - [ ] should ignore correct swap path > 3 legs
  - [ ] should return direct path even if composite swap paths has greater return
  - [ ] should deduct commission fee - 1 leg
  - [ ] should deduct commission and dex fees - 2 legs
  - [ ] should have no swap path - isolated token H
  - [ ] should throw error for invalid tokenId
get all paths
  - [ ] should be bidirectional swap path - listPaths(a, b) === listPaths(b, a)
  - [ ] should get correct swap path - 2 legs
  - [ ] should get correct swap path - 3 legs
  - [ ] should ignore correct swap paths > 3 legs
  - [ ] should get multiple swap paths
  - [ ] should handle cyclic swap paths
  - [ ] should have no swap path - isolated token H
  - [ ] should throw error when fromToken === toToken
  - [ ] should throw error for invalid tokenId
get list swappable tokens
  - [ ] should list correct swappable tokens
  - [ ] should not show status:false tokens
  - [ ] should list no tokens for token that is not swappable with any
  - [ ] should throw error for invalid / non-existent tokenId
latest dex prices
  - [ ] should get latest dex prices - denomination: DFI
  - [ ] should get latest dex prices - denomination: USDT
  - [ ] should get consistent, mathematically sound dex prices - USDT and DFI
  - [ ] should get consistent, mathematically sound dex prices - A and B
  - [ ] should list DAT tokens only - O (non-DAT token) is not included in result
  - [ ] should list DAT tokens only - status:false tokens are excluded
  param validation - denomination
    - [ ] should throw error for invalid denomination

#### governance.controller.defid.ts
governance - listProposals and getProposal
  - [ ] should listProposals
  - [x] should listProposals with size
  - [x] should listProposals with status
  - [x] should listProposals with type
  - [x] should listProposals with cycle
  - [x] should listProposals with status and type
  - [x] should listProposals with status, type and cycle
  - [x] should listProposals with pagination
  - [x] should listProposals with all record when limit is 0
  - [x] should listProposals with all record when all flag is true
  - [x] should listProposals with status and pagination
  - [ ] should listProposals with type and pagination
  - [ ] should listProposals with status, type and pagination
  - [ ] should getProposal for CFP
  - [ ] should getProposal for VOC
governance - listProposalVotes
  - [ ] should listProposalVotes
  - [ ] should listProposalVotes with cycle
  - [ ] should listProposalVotes with all records when limit is 0
  - [ ] should listProposalVotes with all records when all flag is true
  - [ ] should listProposalVotes with all masternodes
  - [ ] should listProposalVotes with all masternodes and cycle
  - [ ] should listProposalVotes with all masternodes, cycle and pagination

#### token.controller.defid.ts
list
  - [ ] should listTokens
  - [x] should listTokens with pagination
  - [x] should listTokens with an empty object if size 100 next 300 which is out of range
get
  - [ ] should get DFI by DFI numeric id
  - [ ] should get DBTC-DETH by DBTC-DETH numeric id
  - [x] should throw error while getting non-existent token

#### fee.controller.defid.ts
fee/estimate
  - [x] should have fee of 0.00005 and not 0.00005 after adding activity

#### stats.controller.defid.ts
  - [x] should getRewardDistribution

#### loan.scheme.controller.defid.ts
loan
  - [x] should listLoanSchemes
  - [x] should listSchemes with pagination
  - [x] should listSchemes with an empty object if size 100 next 300 which is out of range
get
  - [x] should get scheme by symbol (1 ms)
  - [x] should throw error while getting non-existent scheme

#### block.controller.defid.ts
get
  - [x] should get block based on hash
  - [x] get should get block with height
  - [x] should get undefined with invalid hash
list
  - [x] should return paginated list of blocks
  - [x] should return all the blocks if the size is out of range
  - [x] list would return the latest set if next is outside of range
  - [x] list would return the latest set if next is 0
getTransactions
  - [x] should get transactions from a block by hash
  - [x] getTransactions should not get transactions by height
  - [x] getTransactions should get empty array when hash is not valid
  - [x] getTransactions should get empty array when height is not valid
  - [x] should list transactions in the right order
parseHeight
  - [x] should return undefined for negative integer
  - [x] should return undefined for float
  - [x] should return number for positive integers
  - [x] should return undefined for empty string
  - [x] should return undefined for undefined
  - [x] should return undefined for strings with characters
