### ISSUE TITLE
Tracer tracker

### ISSUE THREAD

**Issue by sieniven** [DeFiCh/ain#2839]
## Summary
Implementation for the node's tracer module to be fully compatible with geth and various interfacing block explorers. 

### Required features
- [x] Implementation of tracer service for block traces to handle API calls from debug and trace namespace trace support endpoints - #2845
- [x] Add support for tracer on custom system transactions (transferdomain txs, DST20 deployment/updates) - #2845
- [x] Add caching support to API calls to tracer service - #2875
- [x] Add basic tracer implementation for tracing service - #2873
- [x] Add custom Blockscout tracer input implementation - #2873
- [x] Add custom CallTracer tracer input implementation - #2873
- [x] Correct implementation for evm event listener for basic tracer and custom tracers - #2873
- [x] Correct implementation for gasometer event listener for basic tracer and custom tracers - #2873
- [x] Correct implementation for runtime event listener for basic tracer and custom tracers - #2873
- [x] Bug fixes to incorrect state on trace_transaction execution - #2841 and #2845
- [x] Handle params support for tracer RPC calls - #2845
- [x] Trace transaction API for transaction traces in tracer service - #2841
- [x] Trace block API for block traces in tracer service - #2875
- [x] Trace call API for eth calls with state overrides, for call traces in tracer service - #2876
- [x] Refactor eth_createAccessList listener - #2881

### debug namespace RPCs
- [x] debug_traceTransaction - #2841 and #2873
- [x] debug_traceBlockByNumber - #2875
- [x] debug_traceBlockByHash - #2875
- [x] debug_traceCall - #2876 

### Tests
- [x] Add metachain-ts test suites for all debug / trace namespace RPCs - https://github.com/DeFiCh/metachain-ts-tests/pull/6
- [x] Full integration testing with blockscout compatibility

**Comment by sieniven** [comment]
#2841 and #2845 once merged will resolve the implementation of tracer service, params support, and incorrect state on trace tx execution.

**Comment by sieniven** [comment]
Tracer features will be on production once the following PRs are in:
- #2845
- #2873
- #2875
- #2876
- #2881
