### ISSUE TITLE
Ocean integration tracker

### ISSUE THREAD

**Issue by Jouzo** [DeFiCh/ain#3080]
# Issues :

- [x] Fails to resolve the path and hit 404 on `vaults/<vault_id/auctions/0` see :
https://defiscan.live/vaults/7e9761f1e32389cbb7fed7b1f5bdc8a9cb29bf39e4d6da7f83e6230835d6932f/auctions/0?network=TestNet
https://explorer.mydefichain.com/vaults/7e9761f1e32389cbb7fed7b1f5bdc8a9cb29bf39e4d6da7f83e6230835d6932f/auctions/0?network=TestNet https://github.com/DeFiCh/ain/pull/3100/commits/e37d5e4fa56d7d066f539becd63a9d6689cadee3

- [x] Lightwallet crash
- [ ] TVL discrepancy
- [x] Remove liquidity error : `Transaction is not a composite swap` https://github.com/DeFiCh/ain/pull/3100/commits/7f98835f6913381b42826258486faf78ed9c1757
- [x] Check ocean sync on startup
- [x] Ocean catchup on startup
- [ ] To amount fallback on indexing from snapshot

**Comment by canonbrother** [comment]
> Fails to resolve the path and hit 404 on vaults/<vault_id/auctions/0 see :
https://defiscan.live/vaults/7e9761f1e32389cbb7fed7b1f5bdc8a9cb29bf39e4d6da7f83e6230835d6932f/auctions/0?network=TestNet
https://explorer.mydefichain.com/vaults/7e9761f1e32389cbb7fed7b1f5bdc8a9cb29bf39e4d6da7f83e6230835d6932f/auctions/0?network=TestNet https://github.com/DeFiCh/ain/commit/e37d5e4fa56d7d066f539becd63a9d6689cadee3
hit 404 as url is not correct..
should be 
`https://defiscan.live/vaults/<vault_id>/auctions/<liquidation_height>/batches/<batch_index>/history?network=TestNet`

**Comment by kuegi** [comment]
vault data is missing oracle prices. activePrice objects are there but all are 
```json
"activePrice":{"active":null,"next":null,"isLive":false,"block":{"hash":"11421225633bb7c3c5ce93b30658c894213290d0df513c203d3199a3a851445d","height":686314,"time":1635870812,"medianTime":1635870550}}
```
